---
name: "wp bolt image build and deployment"
on:
  push:
    branches:
      - dev
  repository_dispatch:
    types: [event_causedby_image_repochange]
                      
jobs:
                        
  build:
    runs-on: ubuntu-latest
    env:
      terraform_version: "1.9.4"

    steps:

      - name: "checkout repo"
        uses: actions/checkout@v3

      - name: "terraform installation"
        uses: hashicorp/setup-terraform@main
        with:
          terraform_version: 1.6.2

      - name: "terraform init"
        run: |
          terraform init \
             -backend-config="bucket=${{secrets.dev_bucket}}" \
             -backend-config="key=terraform.tfstate" \
             -backend-config="region=${{secrets.DEV_REGION}}" \
             -backend-config="access_key=${{secrets.DEV_ACCESSKEY}}" \
             -backend-config="secret_key=${{secrets.DEV_SECRETKEY}}"

      - name: "terraform validate"
        run: terraform validate

      - name: "format terraform files"
        run : terraform fmt

      - name: "terraform plan"
        run : |
          terraform plan -var-file=dev.tfvars
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_ACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_SECRETKEY }}
          AWS_DEFAULT_REGION : ${{ secrets.DEV_REGION }}

      - name: "terraform apply"
        run: |
          terraform apply \
            -auto-approve \
            -var-file="dev.tfvars" 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_ACCESSKEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_SECRETKEY }}
          AWS_DEFAULT_REGION : ${{ secrets.DEV_REGION }}
